quarkus.http.port=8080
quarkus.rest-client.station-zero.url=https://station-zero-player2.apps.cluster-spq9k.spq9k.sandbox5413.opentlc.com
quarkus.tls.trust-all=true
quarkus.rest-client.station-zero.trust-store=
quarkus.openshift.build-strategy=docker
quarkus.container-image.build=true
# Optional: Expose a route to access the service
quarkus.openshift.route.expose=true

# Station Zero validation endpoint
brushpass.validate-url=https://station-zero-player2.apps.cluster-spq9k.spq9k.sandbox5413.opentlc.com/validate/pin