quarkus.http.port=8080
quarkus.rest-client.station-zero.url=https://station-zero-player1.apps.cluster-spq9k.spq9k.sandbox5413.opentlc.com
quarkus.tls.trust-all=true
quarkus.rest-client.station-zero.trust-store=
